
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
#http:
#  base_url: https://marionguillaume.fr
#  server_port: 8123
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem

# Text to speech
tts:
  - platform: google_translate

#lovelace:
#  mode: yaml


climate:
  - platform: generic_thermostat
    name: climateDiane
    heater: switch.switch_state_revert
    target_sensor: sensor.0x00158d000411b5e5_temperature
    min_temp: 10
    max_temp: 25
    ac_mode: false
    target_temp: 19
    cold_tolerance: 0.2
    hot_tolerance: 0.2
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode: "heat"
    away_temp: 14
    precision: 0.1

switch:
  - platform: template
    switches:
      switch_state_revert:
        value_template: "{{ is_state('switch.0x00158d000444ed09_switch_l2', 'off')}}"
        turn_on:
          service: switch.turn_off
          data:
            entity_id: switch.0x00158d000444ed09_switch_l2
        turn_off:
          service: switch.turn_on
          data:
            entity_id: switch.0x00158d000444ed09_switch_l2


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
frontend:
  themes: !include themes.yaml
